### ISSUE TITLE
Update demos to conform to the new directory structure

### ISSUE THREAD

**Issue by panno8M** [godot-nim/demo#17]
related to godot-nim/gdextshell#32

It also serves as a test for the `gdextwiz new-workspace` command.

**Comment by insomniacUNDERSCORElemon** [comment]
I have my own project pretty much converted on my own machine except for the move from nimble-->bootstrap. Would it be fine if I just delete the folder and re-uploaded it? It would be much easier for me than alternatives, though it may ruin the file history.

Also, I left the movement demo as an addon on the grounds that it is self-contained and not a needed thing for the project. Though I'm not sure how you feel about "fake" addons, especially before published addons exist. EDIT: I could have it as an extension that isn't in the addons folder.

**Comment by panno8M** [comment]
This was completely my fault, but I suggested so many different configurations that I lost track of what would be a success.
I want to just fix it so that the build passes with the latest libraries, adjust it so that the version number can be managed properly (not fixed at v0.1.0 as it is now), and then think about it again.

In the meantime, could you please list the issues on the actual product, especially the structure of the demo that are being raised now, sorted by level, in this thread.

**Comment by insomniacUNDERSCORElemon** [comment]
> In the meantime, could you please list the issues on the actual product, especially the structure of the demo that are being raised now, sorted by level, in this thread.

The main thing is probably that I like the bootstrap format/name that you suggested, and a static name for the entry point file means that I can use build with 1 command across multiple extensions+projects in my editor. I imagine that finding all of a known-name file in `res://` might allow building from the editor without needing build hooks, but that's just thinking out loud again.

It took me a minute or two to get the basic idea of you changing that, and while it's neat that it's possible I do not like the method of the .cfg files.

Another preference, but I'd prefer as few folders as necessary. That's mainly the issue here: `/dtc2d/src/dtc2d/classes` (you could end that at /src/, no other files are there). I know you probably did that to make it obvious in the import lines that you redefined the src location, but still. Though I guess at least on github you only need one click to get there from the 1st dtc2d folder.

I think the important part of the creeps demo is in the functionality thus I doubt many will use it as anything more than another reference, and I have a PR up now with how I prefer it (including my demo) anyways. So ultimately the rest is up to you here and w/addon_template. At least assuming the format I went with will continue working. 

It's fine, and I know I should stop talking out loud about details that belong to the future and get to trying out other things.
